### ISSUE TITLE
0s in 1s place are ignored

### ISSUE THREAD

**Issue by eli-oat** [GreenImp/rpg-dice-roller#10]
E.g. 3d6+10 results in [4,4,1]+1 = 10, or d20+40 results in [6]+4 = 10 while d20+42 results in[2]+42 = 44

**Comment by GreenImp** [comment]
You're absolutely correct! I'm not sure how I missed this.

I'll get a fix in as soon as I can.

**Comment by GreenImp** [comment]
I've just pushed up a change and new release (v1.2.1), which fixes this bug.

**Comment by eli-oat** [comment]
💯 Thanks for the quick fix!

**Comment by GreenImp** [comment]
No worries.
