### ISSUE TITLE
Upgrading to 4.0.0 breaks nodejs require

### ISSUE THREAD

**Issue by TheCraiggers** [GreenImp/rpg-dice-roller#100]
**Describe the bug**
Everything was fine in 3.1.5 but after upgrading to version 4 my project refuses to run due to the following error:

(node:65267) Warning: require() of ES modules is not supported.

This is just from using the instructions in the README. My code is as follows:
const { DiceRoller } = require('rpg-dice-roller');
const roller = new DiceRoller();

**To Reproduce**
1. npm i rpg-dice-roller
2. Add the require statement from the README
3. Attempt to run

**Expected behavior**
I expect the module to be imported with the require function.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - NodeJS v13.3.0

**Additional context**
Reverting back to last version fixes issue.

**Comment by GreenImp** [comment]
You're right! Sorry about that. I'm looking into solutions now.

Just to clarify, you're using nodeJS 13.3.0?
Is it in a library that uses ES6 modules, through `import`, or commonjs style using `require`?

**Comment by GreenImp** [comment]
Okay, I've seen your Discord bot where you're using the dice roller: https://github.com/TheCraiggers/Pathfinder-Discord-Bot/blob/afbc264b50fd86aaf10d2901ce79c1715f0ee8d1/modules/omni-tracker.js#L53

I can see you're using commonJS style require / export.
It looks like there's a bug when trying to call an ES module in a commonJS node project. I'm working on a fix now.

**Comment by GreenImp** [comment]
I've just published v4.0.1, which will hopefully fix your issue. Once you've updated, you should be able to `require` the dice roller like this (Note the path to the UMD script after teh package name):

```js
// include individual modules
const { DiceRoller, StandardDice } = require('rpg-dice-roller/lib/umd/bundle.js');

// import everything and store it on the `rpgDiceRoller` scope
const rpgDiceRoller = require('rpg-dice-roller/lib/umd/bundle.js');
```

Let me know if it works for you.

**Comment by TheCraiggers** [comment]
Wow, thanks for the awesomely fast turnaround on this; sorry I wasn't able to respond today. I followed the new instructions and everything is working now.

I feel like this is something I should have been able to fix myself and submit a PR for, but I haven't done JS since Netscape was a thing. All this ES6 stuff is bonkers crazy. Thanks for helping a noob out and for your great library.

**Comment by GreenImp** [comment]
I'm glad I could help :) I'm just glad people are using it!

ES6 really changed JS a lot. For the better I'd say, but it is a big learning curve.
