### ISSUE TITLE
Adding negative numbers doesn't work.

### ISSUE THREAD

**Issue by TheCraiggers** [GreenImp/rpg-dice-roller#103]
**Describe the bug**
Typically, it's not all that uncommon in math to see something like 5+-2 but this fails parsing in dice roller. This would be even more important if you're using this in a library where you may not exactly know what values references may have when building a dice notation string.

**To Reproduce**
1. Make a new DiceRoller
2. roll something like 1d20+-5

**Expected behavior**
The bot rolls 1d20 and then subtracts 5 from the result

**Additional context**
This was on NodeJS v13

**Comment by GreenImp** [comment]
Good spot! Should hopefully be a simple fix. I'll look at it this week and try and get a fix out.

**Comment by GreenImp** [comment]
This has been fixed in pull request #104 and has gone out in v4.0.2
