### ISSUE TITLE
Google Apps scripts

### ISSUE THREAD

**Issue by MotoMeltar** [GreenImp/rpg-dice-roller#105]
could you publish this die roller as a Google Apps Script library, so it could be consumed by third parties? I found your code so usefull, and would love to use it in my Telegram Dungeon World RPG bot.

Thanks

**Comment by GreenImp** [comment]
Hi @MotoMeltar!

Is Google Apps script not just for use within Google docs, sheets etc? I can't seem to find any refernce of using it outside of that ecosystem, or a way to add a library not written in scripts into their library.

Does Telegram specifically use Google App Scripts?

The dice roller is available on [NPM](https://www.npmjs.com/package/rpg-dice-roller).

If you can give me some more information, I can look into it.

**Comment by MotoMeltar** [comment]
Thank you for your interest.

Google Apps Script provides free hosting and service of javascript based apps and web pages, and offers a lot of interfaces to interact with google services. That was my main motivator, as I wanted to develop a TelegramBot that read from a google spreadsheet and rolled according to those values. So if I use the command /fue, the bot will roll 2d6+(fue modifier) and award me an XP if the result is a failure (6 or less, in dungeon world).

Telegram does not require you to develop your bots in anything. But it's interface provides a WebHook so you can reroute the calls to the bot to anything. So it was easy to link both products.

But I made a mistake during development: My mechanics are all interlinked beetween each other. So if I want to develop another bot (I'm thinking Lady Blackbird for my next trick) I would have to copy-paste everything relevant to the new bot. Or I could take parts of that code and make Google Apps Script libraries, as documented here: https://developers.google.com/apps-script/guides/libraries

There are parts of my code (processing the Telegram message and linking a google sheet to the user/chat where is called) that I have to publish as a library, that's for sure. But, as you can share libraries, I thought maybe ther already is one?

Looking around github I found no one had a dice roller library for Google Apps Script, and by chance found your dice roller. It was exactly what I needed! but Google Apps Script does not let me get the code published anywhere. 

don't get me wrong: If it's any trouble I'll create my own. But no harm in asking, is there? thanks for your time and interest.

**Comment by GreenImp** [comment]
I'm not this that this is that feasible. It looks like it would require re-writing the library as a GAS project, but there's a lot of JS functions in the library that don't work in GAS.

It does look like it _may_ be possible to include NPM packages in GAS. I found this article, just gave it a cursory glance so not certain: https://blog.gsmart.in/es6-and-npm-modules-in-google-apps-script/
The NPM package has a compiled version of the library that may or amy not be compatible.
