### ISSUE TITLE
readme.md says d% range is [0, 100] but instead of [1, 100]

### ISSUE THREAD

**Issue by sigfriedmcwild** [GreenImp/rpg-dice-roller#107]
This seems to be a minor documentation bug:
in the supported notation section:
> Percentile dice roll a whole number between `0-100`, and are specified with the format `d%`.

It should say "between 1-100" instead

**Comment by GreenImp** [comment]
Good spot! I'll get that sorted.

**Comment by GreenImp** [comment]
This has been fixed and will go out in the v4.1.0
