### ISSUE TITLE
Function to return dice roll range?

### ISSUE THREAD

**Issue by JamesSkemp** [GreenImp/rpg-dice-roller#150]
I thought for sure there was a function that would return the possible range of results for a dice notation.

For example, `1d4` would return a min of 1 and a max of 4. `1d6+3` would return the range of 4-9.

I did try to use the search on https://greenimp.github.io/rpg-dice-roller/api/Parser.html#static-methods but was getting no obvious change, and no errors logged in the console.

**Comment by GreenImp** [comment]
Not sure what you mean about the search "getting no obvious change"?

There's currently no built-in function for doing this, but I can really see a code use-case for it. I'll take a look at implementing something.

At present, you would have to do it manually, which isn't too difficult for for dice rolls, but obviously gets rather complicated if you've got modifiers and such.

Arguably not ideal but, each die object has a min and max value, which is the range that it can roll. You can manually create an instance of a Die object and read the `min` / `max` values on it.
There are currently 3 different types of dice; `StandardDice` (simple numeric dice, min of 1, max whatever you define), `FudgeDice`, and `PercentileDice`. They're found in `src/dice/`.

So you can do something like:
```
import { Dice } from `rpg-dice-roller`;

// first argument is notation, second is qty rolled, third is number of sides
const die = new StandardDice('1d6', 1, 6);

console.log(die.min); // outputs 1
console.log(die.max); // outputs 6

// min and max are just the range of a single die - rolling multiple will return the same min and max
const die = new StandardDice('2d6', 2, 6);

console.log(die.min); // outputs 1
console.log(die.max); // outputs 6
```

Unfortunately, if you had something like `2d6+1`, you would have to calculate it yourself.
Also, the die objects aren't  currently documented, but I've opened a ticket to remind myself to add it: https://github.com/GreenImp/rpg-dice-roller-docs/issues/3

Obviously, that solution isn't ideal, but I'll look into adding a built in way of doing it.

**Comment by JamesSkemp** [comment]
**Search**: sorry, that could have had better grammar. I blame it being after midnight when I wrote it. 😁 

First time I've used the new docs site (looks nice, by the way) and I was trying to use the search to find a few terms. Entering `range` or `min`, and pressing enter or the magnifying glass, didn't appear to be doing anything. Trying it again this morning it looks like it's only pulling up select terms, and just doesn't show a message if there's no match.


**Min/max**: Drat, but I at least know for my particular implementation that there should only be standard dice so I can use that workaround for now.

Thanks!

**Comment by GreenImp** [comment]
Ah yeah, I see what you mean about the search, I hadn't noticed. Not sure if I can get it to show a message if there's no results, which is a pain. At the moment, the search just looks at page headers, but I'm going to get it to use Algolia, so it'll be more reliable. (https://github.com/GreenImp/rpg-dice-roller-docs/issues/6)

I'm glad you like the site though, thanks :)

I'll open this ticket open and look into adding the functionality in the future.

**Comment by GreenImp** [comment]
Just thought it worth mentioning that the docs are now using Algolia search, so should be far better and they do now show a message if there aren't nay results.

**Comment by GreenImp** [comment]
My current thinking with this is to add a `minTotal`, and `maxTotal` to the `DiceRoll` object, so it will have 3 totals:

* `total`: the actual total rolled
* `minTotal`: the minimum possible total that can be rolled
* `maxTotal`: the maximum possible total that can be rolled

I think this also ties in nicely with #140 which needs an average total, so I can calculate it from the min / max totals.

**Comment by GreenImp** [comment]
I've got this _mostly_ working, but have hit a snag when using some modifiers; mainly explode.

For example, `2d10!` will explode every time the max value (10) is rolled, which means that trying to get the max possible value causes it to infinitely explode, in a never-ending loop.

This is exactly the same issue as has been raised in #137, so I'm going to have to come up with a solution for that before I can resolve this one.

**Comment by JamesSkemp** [comment]
Ah, exploding dice. Maybe a quick check and return of `Infinity` ... ?

I didn't get to it yesterday, but I'll remind myself of my use case and use the new search to see if there's something else already as a property that I can use.

**Comment by GreenImp** [comment]
My current plan is to limit exploding to 1000 per dice roll.

```
// this would produce 1001 rolls; the initial roll, and 1000 exploded rolls
1d10!

// this would produce 2002 rolls; the initial 2 rolls, and 100 exploded rolls per initial roll
2d10!
```

I'll need to do the same with the reroll modifier as well.

**Comment by GreenImp** [comment]
I've got this working! There's now `minTotal` and `maxTotal` properties on the `DiceRoll` object.

The only thing to be aware of is that it can be slow to calculate the `maxTotal` if you're exploding on the highest value like `999d10!`, especially if rolling a high qty of dice.

**Comment by GreenImp** [comment]
Just as an example, you'll be able to do this:

```javascript
const diceRoll = new DiceRoll('4d8+1');

console.log(diceRoll.minTotal); // outputs 5
console.log(diceRoll.maxTotal); // outputs 33
```

**Comment by GreenImp** [comment]
There's also an `averageTotal` that will be released with this as well. I've updated the example above to show it.
