### ISSUE TITLE
Allow manual building of dice rolls

### ISSUE THREAD

**Issue by GreenImp** [GreenImp/rpg-dice-roller#17]
We could potentially open up the `DiceRoll` class to allow manual building of the object, by passing in the notation, and list of rolls.

The rolls passed in would need validating against the notation.

This would allow us to programatically populate dice rolls, which could be handy for saving and loading of rolls.

**Comment by sheibeck** [comment]
I'm using your library on my site and just had a user ask if they could share a roll log with another user. Just wanted to bump this ;)

**Comment by GreenImp** [comment]
That's a perfect example of a use case for this functionality.
Thanks for bumping as it was quite a low priority, but I'll class it as more important.

I'm working on a couple of things for the dice roller at the moment, but I'm also in the process of moving house, so it's taking a bit longer than I'd like.

**Comment by GreenImp** [comment]
I'm still working on this but I've got it partially complete in the [17-Allow-manual-building-of-dice-rolls](https://github.com/GreenImp/rpg-dice-roller/tree/feature/17-Allow-manual-building-of-dice-rolls) feature branch.

Currently, you can export and import single `DiceRoll` objects, but not an entire roll log, on the `DiceRoller` object.

There's an example of how to use in the readme now, on that branch.

```js
      // roll a single notation without saving it to the log
      var diceRoll = new DiceRoll('2d6-L');
      
      // export the dice roll
      var exportedData = diceRoll.export(DiceRoll.exportFormats.JSON);
      
      // we can also import data either from a previous export, or built up manually
      // Note that here we're calling `import` on the `DiceRoll` class, not an existing object
      var importedDiceRoll = DiceRoll.import(exportedData, DiceRoll.exportFormats.JSON);
```

You could also get a diceRoll from a `DiceRoller` log if you like as well:

```js
      // create a new instance of the DiceRoller
      var diceRoller = new DiceRoller();
    
      // roll the dice a few times
      diceRoller.roll('4d20-L');
      diceRoller.roll('1d6');
      diceRoller.roll('10d10-L');
      
      // get the latest dice rolls from the log
      var latestRoll  = diceRoller.getLog().shift();
      
      // export the dice roll
      var exportedData = latestRoll.export(DiceRoll.exportFormats.JSON);

      // or loop through each roll
      diceRoller.getLog().forEach(function(diceRoll){
            var exportedData = diceRoll.export(DiceRoll.exportFormats.JSON);
      });
```

You can currently encode as either JSON or base64 (for easy sending in URLs etc). So a user can export their rolls, send the data output to the other user, who can then import it on their end.
At present, you need to specify the format when importing, but I'm going to change it to detect the format automatically.
Also, if no format is specified during export, it will default to JSON.

I'll get exporting / importing of the entire roll log sorted, so it doesn't have to be done manually, like above.
Hopefully that will provide you with what you need for this. If not, lt me know.

**Comment by GreenImp** [comment]
Okay, I've got it working so that you can now import / export an entire `DiceRoller` object, so an entire roll log.

It works the same way as importing / exporting `DiceRoll`s, but you call it on the `DiceRoller` instead.
There are some examples in the [readme](https://github.com/GreenImp/rpg-dice-roller/tree/feature/17-Allow-manual-building-of-dice-rolls#usage).

In short:

### Exporting
```js
// create a new instance of the DiceRoller
var roller  = new DiceRoller();

// roll the dice several times
roller.roll('4d20-L');
roller.roll('2d6');
roller.roll('8d10+L');

// export the roller, including all DiceRolls in the roll log
var exportedRoller = roller.export(DiceRoller.exportFormats.BASE_64);
```

### Importing
```js
// call the static import method to create a new DiceRoller with the exported data
var roller2 = DiceRoller.import(exportedRoller);

// OR

// manually create a DiceRoller object
var roller3 = new DiceRoller();

// call the import method on the DiceRoller object to import the data and append it to the existing roll log
// this method allows us to import multiple roll data sets and join them in to a single DiceRoller
roller3.import(exportedData);

// add a normal roll to the log, retaining the imported rolls
roller3.roll('1d6');

// append more roll data, still keeping all previous imports and rolls
roller3.import(otherExportedData);
```

It's still currently in it's own [feature branch](https://github.com/GreenImp/rpg-dice-roller/tree/feature/17-Allow-manual-building-of-dice-rolls), but I'll merge it in to the next release.
Hopefully you can use it from the feature branch. If not, give me a shout and I'll try and get it merged into a release sooner.

**Comment by GreenImp** [comment]
No worries. Let me know if you find any issues, or it doesn't work as you'd expected.

**Comment by sheibeck** [comment]
Will do. Hoping to get some time this week to implement.
