### ISSUE TITLE
+0 Generates error

### ISSUE THREAD

**Issue by iamromeo** [GreenImp/rpg-dice-roller#199]
**Describe the bug**
When a user inputs +0 e.g. 1d20+0 the script responds with an error. 

Please note that this was actually working as expected on the previous version. 

**Expected behavior**
Return a result with the addition of 0 or simply ignore it

**Error Produced**

bundle.min.js:10 Uncaught SyntaxError: Unexpected end of expression (char 3)
    at ct (bundle.min.js:10)
    at bundle.min.js:10
    at bundle.min.js:10
    at bundle.min.js:10
    at bundle.min.js:10
    at bundle.min.js:10
    at bundle.min.js:10
    at bundle.min.js:10
    at bundle.min.js:10
    at bundle.min.js:10
ct @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
et @ bundle.min.js:10
tt @ bundle.min.js:10
Y @ bundle.min.js:10
Q @ bundle.min.js:10
K @ bundle.min.js:10
Z @ bundle.min.js:10
X @ bundle.min.js:10
G @ bundle.min.js:10
$ @ bundle.min.js:10
V @ bundle.min.js:10
H @ bundle.min.js:10
z @ bundle.min.js:10
W @ bundle.min.js:10
q @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
B @ bundle.min.js:10
(anonymous) @ bundle.min.js:10
L @ bundle.min.js:10
b @ bundle.min.js:10
string @ bundle.min.js:10
compile @ bundle.min.js:10
cn @ bundle.min.js:10
get @ bundle.min.js:10
get @ bundle.min.js:10
go @ bundle.min.js:10
get @ bundle.min.js:10
get @ bundle.min.js:10
value @ bundle.min.js:10
(anonymous) @ global.js?v=01169:546
dispatch @ global.js?v=01169:1
v.handle @ global.js?v=01169:1
Show 14 more frames

**Comment by Tillerz** [comment]
I guess that's why:

grammar.pegjs: IntegerNumber  = [1-9] [0-9]* { return parseInt(text(), 10) }

So a 0 is not allowed because numbers are only allowed to start with 1 to 9.

**Comment by GreenImp** [comment]
Hey guys. That could definitely not throw an error!
Is this on the latest version (4.5.1)? I'll take a look.

**Comment by Tillerz** [comment]
Just checked, yes, it's 4.5.1

**Comment by GreenImp** [comment]
Okay, that should be fixed now, in v4.5.2. Let me know if you have any issues!

**Comment by iamromeo** [comment]
Confirmed - working - will deploy new version on World Anvil thank you so much @GreenImp for the amazingly quick response.
