### ISSUE TITLE
Demo rolls return unexpected results

### ISSUE THREAD

**Issue by rexxmagnus** [GreenImp/rpg-dice-roller#231]
On the demo pages, the samples that say
4d6d1 + 5
will return a result like
4d6d1 + 5: [1d, 4, 6, 3]+5 = 18 

I would have expected this to roll 4d6, 1d6, add 5 and sum the result.
According to the output, the result is actually rolling 3d6, 1d6 + 5
Repeated rolls will have the d in a different array element with a random number between 1-6 prefixing it.

**Comment by GreenImp** [comment]
The returned result looks correct to me.

This notation, `4d6d1 + 5` means "Roll a 6 sided die 4 times, and drop (ignore) the lowest result. Add the rolls together and add 5."
If you've not seen it yet, I'd check out the documentation on the "drop" modifier (Which is being used here): https://greenimp.github.io/rpg-dice-roller/guide/notation/modifiers.html#drop-d-n-dh-n-dl-n

If you think it's still not right, let me know!

**Comment by rexxmagnus** [comment]
Ah, gods, my mistake! I'll close this as a non-issue.

**Comment by GreenImp** [comment]
No worries!
