### ISSUE TITLE
NodeJs 'flat is not a function'

### ISSUE THREAD

**Issue by OlivierDa** [GreenImp/rpg-dice-roller#80]
With the latest version : 3.1.1 : 
`TypeError: Array.prototype.map.apply(...).flat is not a function`
It seems that flat is also nodejs11+:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

Thanks in advance!

**Comment by GreenImp** [comment]
I saw your comment on #78 as well. I thought `.flat()` was supported in everything, woops.
Sorry that it didn't work for you! I'll get a polyfill in for that now as well.

**Comment by GreenImp** [comment]
Okay, that polyfill has been merged in #81, and added in v3.1.2.
Let me know if you have any more issues. Unfortunately I don't currently have any versions of node < v11 installed, but will look to getting something set up if there are more issues.

**Comment by GreenImp** [comment]
Just a heads up; I found an issue with the published package on npm for V3.1.2.
It didn't have the correct bundled js files included and threw a wobbly if you didn't have rollup installed. This has been fixed and released as v3.1.3.

Let me know if you have any issues.
