### ISSUE TITLE
Storytelling System type dice

### ISSUE THREAD

**Issue by iamromeo** [GreenImp/rpg-dice-roller#91]
This is a feature that will allow players of the Storytelling system to get clear results with one dice roll. 

roll a dice pool target number 8+ and explode 9+ and if so how

In the Roll20 standard I would type /roll 6d10>=8!>=9 but that does not seem to work or /roll 6d10>7!>8

**Comment by GreenImp** [comment]
Exploding and pool dice currently don't work together, but I definitely think they should.

I'm in the process of rebuilding parts of the notation parser to allow greater flexibility for things like this. I've not got a timeframe for it but, once complete, it should make the notation much more compatible with the expected syntax for people coming from Roll20, which I seem to get the most requests for.

**Comment by iamromeo** [comment]
Hey @GreenImp by the way this Dimitris the Developer of World Anvil. I am using your amazing work on World Anvil and I would very much be interested to give you a boost/hire you for the hours will take to do this :) If you are interested pop me a message at hello@worldanvil.com my good sir.

**Comment by GreenImp** [comment]
Hey @iamromeo sorry for the delay. I've sent you an email :)

**Comment by GreenImp** [comment]
Hey @iamromeo I just want to double-check expected output and that I understand correctly.

If I roll:
```
6d10>=8!>=9
```
You would expect it to explode any that are greater than or equal to 9.
Out of all the rolls (Including exploded ones), any that are greater than or equal to eight should be classed as a success.

So something like (Asterisk means success, exclamation mark is exploded):
```
6d10>=8!>=9: [4,8*,9*!,4,1,2,9*!,6] = 3 successes
```

If so, I've got that pretty much working in the rebuild. I need to get the number of success working, but using both modifiers in combination is working.

**Comment by GreenImp** [comment]
Assuming that my previous message is correct, I've now got this working (Currently on the `feature/enhanced-parsing-engine` branch).
I've still got some work to do on the engine before I can release it though, but I'll mark this as closed.
